version: '3.9'

services:

  fidelis-oracle:
    image: gvenzl/oracle-xe
    container_name: fidelis-oracle

    ports:
      - "1521:1521"

    environment:
      ORACLE_PASSWORD: fidelis

    volumes:
      - oracle_data:/opt/oracle/oradata

    restart: always

  fidelis-api:
    build: .

    container_name: fidelis-api

    ports:
      - "8080:8080"

    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__FidelisOracle: Data Source=fidelis-oracle:1521/XEPDB1;User Id=system;Password=fidelis;

    depends_on:
      - fidelis-oracle

    command:
      sh -c "sleep 40 && dotnet Fidelis.Api.ddl"

    restart: always

volumes:
  oracle_data: