version: '3.9'

services:

  fidelis-api:
    image: nginx
    container_name: fidelis-api
    ports:
      - "8080:80"
    restart: always

  fidelis-oracle:
    image: gvenzl/oracle-xe
    container_name: fidelis-oracle

    ports:
      - "1521:1521"

    environment:
      ORACLE_PASSWORD: fidelis

    volumes:
      - oracle_data:/opt/oracle/oradata

    restart: always

volumes:
  oracle_data: