-- Script de criação do banco do projeto Fidelis.
-- Estrutura principal para gestão de clínica, tutor, pet e histórico veterinário.

CREATE TABLE `CLINICAS` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `Nome` VARCHAR(100) NOT NULL,
    `Cnpj` VARCHAR(18) NOT NULL,
    `Telefone` VARCHAR(15) NOT NULL,
    `Email` VARCHAR(75) NOT NULL,
    `Endereco` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dados básicos do tutor responsável pelo pet.
CREATE TABLE `TUTORES` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `Cpf` VARCHAR(14) NOT NULL,
    `Nome` VARCHAR(75) NOT NULL,
    `Email` VARCHAR(75) NOT NULL,
    `Senha` VARCHAR(50) NOT NULL,
    `Telefone` VARCHAR(15) NOT NULL,
    `Endereco` VARCHAR(255) NOT NULL,
    `DataCriacao` DATETIME(6) NOT NULL,
    PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Veterinários vinculados à clínica.
CREATE TABLE `VETERINARIOS` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `Crmv` VARCHAR(13) NOT NULL,
    `Nome` VARCHAR(75) NOT NULL,
    `Email` VARCHAR(75) NOT NULL,
    `Senha` VARCHAR(50) NOT NULL,
    `Especialidade` VARCHAR(50) NOT NULL,
    `DataCriacao` DATETIME(6) NOT NULL,
    `ClinicaId` INT NOT NULL,
    PRIMARY KEY (`Id`),
    CONSTRAINT `FK_VETERINARIOS_CLINICAS` FOREIGN KEY (`ClinicaId`) REFERENCES `CLINICAS` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Cadastro principal do pet.
CREATE TABLE `PETS` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `Nome` VARCHAR(30) NOT NULL,
    `Especie` VARCHAR(20) NOT NULL,
    `Raca` VARCHAR(20) NOT NULL,
    `Sexo` VARCHAR(1) NOT NULL,
    `DataNascimento` DATETIME(6) NOT NULL,
    `Status` VARCHAR(1) NOT NULL,
    `FotoUrl` VARCHAR(255) NOT NULL,
    `TutorId` INT NOT NULL,
    `ClinicaId` INT NULL,
    PRIMARY KEY (`Id`),
    CONSTRAINT `FK_PETS_TUTORES` FOREIGN KEY (`TutorId`) REFERENCES `TUTORES` (`Id`),
    CONSTRAINT `FK_PETS_CLINICAS` FOREIGN KEY (`ClinicaId`) REFERENCES `CLINICAS` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Registros de atendimento e evolução clínica do pet.
CREATE TABLE `CONSULTAS` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `DataHora` DATETIME(6) NOT NULL,
    `Tipo` VARCHAR(50) NOT NULL,
    `Diagnostico` LONGTEXT NULL,
    `Observacoes` LONGTEXT NULL,
    `DataRetorno` DATETIME(6) NULL,
    `VeterinarioId` INT NOT NULL,
    `PetId` INT NOT NULL,
    PRIMARY KEY (`Id`),
    CONSTRAINT `FK_CONSULTAS_VETERINARIOS` FOREIGN KEY (`VeterinarioId`) REFERENCES `VETERINARIOS` (`Id`),
    CONSTRAINT `FK_CONSULTAS_PETS` FOREIGN KEY (`PetId`) REFERENCES `PETS` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `EXAMES` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `Tipo` VARCHAR(50) NOT NULL,
    `Descricao` LONGTEXT NOT NULL,
    `Resultado` LONGTEXT NULL,
    `Data` DATETIME(6) NOT NULL,
    `ConsultaId` INT NOT NULL,
    PRIMARY KEY (`Id`),
    CONSTRAINT `FK_EXAMES_CONSULTAS` FOREIGN KEY (`ConsultaId`) REFERENCES `CONSULTAS` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `PRESCRICOES` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `Dosagem` VARCHAR(50) NOT NULL,
    `Frequencia` VARCHAR(50) NOT NULL,
    `DuracaoDias` INT NOT NULL,
    `Observacao` LONGTEXT NULL,
    `ConsultaId` INT NOT NULL,
    PRIMARY KEY (`Id`),
    CONSTRAINT `FK_PRESCRICOES_CONSULTAS` FOREIGN KEY (`ConsultaId`) REFERENCES `CONSULTAS` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `MEDICAMENTOS` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `Nome` VARCHAR(50) NOT NULL,
    `Descricao` LONGTEXT NOT NULL,
    `PrescricaoId` INT NOT NULL,
    PRIMARY KEY (`Id`),
    CONSTRAINT `FK_MEDICAMENTOS_PRESCRICOES` FOREIGN KEY (`PrescricaoId`) REFERENCES `PRESCRICOES` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Evolução do peso e monitoramento da saúde do pet.
CREATE TABLE `HISTORICO_PESOS` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `PesoKg` DECIMAL(7,2) NOT NULL,
    `DataMedicao` DATETIME(6) NOT NULL,
    `Observacao` LONGTEXT NULL,
    `PetId` INT NOT NULL,
    PRIMARY KEY (`Id`),
    CONSTRAINT `FK_HISTORICO_PESOS_PETS` FOREIGN KEY (`PetId`) REFERENCES `PETS` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Lembretes e alertas para o tutor.
CREATE TABLE `LEMBRETES` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `Tipo` VARCHAR(50) NOT NULL,
    `Descricao` LONGTEXT NOT NULL,
    `DataPrevista` DATETIME(6) NOT NULL,
    `Status` VARCHAR(1) NOT NULL,
    `TutorId` INT NOT NULL,
    `PetId` INT NOT NULL,
    PRIMARY KEY (`Id`),
    CONSTRAINT `FK_LEMBRETES_TUTORES` FOREIGN KEY (`TutorId`) REFERENCES `TUTORES` (`Id`),
    CONSTRAINT `FK_LEMBRETES_PETS` FOREIGN KEY (`PetId`) REFERENCES `PETS` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Orientações preventivas e recomendações de cuidado.
CREATE TABLE `RECOMENDACOES` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `Tipo` VARCHAR(50) NOT NULL,
    `Descricao` LONGTEXT NOT NULL,
    `DataRecomendacao` DATETIME(6) NOT NULL,
    `PetId` INT NOT NULL,
    PRIMARY KEY (`Id`),
    CONSTRAINT `FK_RECOMENDACOES_PETS` FOREIGN KEY (`PetId`) REFERENCES `PETS` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `VACINACOES` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `DataAplicacao` DATETIME(6) NOT NULL,
    `DataProxima` DATETIME(6) NOT NULL,
    `VacinaAplicada` VARCHAR(50) NOT NULL,
    `Observacao` LONGTEXT NULL,
    `PetId` INT NOT NULL,
    `VeterinarioId` INT NOT NULL,
    PRIMARY KEY (`Id`),
    CONSTRAINT `FK_VACINACOES_PETS` FOREIGN KEY (`PetId`) REFERENCES `PETS` (`Id`),
    CONSTRAINT `FK_VACINACOES_VETERINARIOS` FOREIGN KEY (`VeterinarioId`) REFERENCES `VETERINARIOS` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `VERMIFUGACOES` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `Produto` VARCHAR(50) NOT NULL,
    `DataAplicacao` DATETIME(6) NOT NULL,
    `DataProxima` DATETIME(6) NOT NULL,
    `PetId` INT NOT NULL,
    `VeterinarioId` INT NOT NULL,
    PRIMARY KEY (`Id`),
    CONSTRAINT `FK_VERMIFUGACOES_PETS` FOREIGN KEY (`PetId`) REFERENCES `PETS` (`Id`),
    CONSTRAINT `FK_VERMIFUGACOES_VETERINARIOS` FOREIGN KEY (`VeterinarioId`) REFERENCES `VETERINARIOS` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `COMPORTAMENTOS` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `Data` DATETIME(6) NOT NULL,
    `Descricao` LONGTEXT NOT NULL,
    `PetId` INT NOT NULL,
    PRIMARY KEY (`Id`),
    CONSTRAINT `FK_COMPORTAMENTOS_PETS` FOREIGN KEY (`PetId`) REFERENCES `PETS` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX `IX_VETERINARIOS_CLINICA` ON `VETERINARIOS` (`ClinicaId`);
CREATE INDEX `IX_PETS_TUTOR` ON `PETS` (`TutorId`);
CREATE INDEX `IX_PETS_CLINICA` ON `PETS` (`ClinicaId`);
CREATE INDEX `IX_CONSULTAS_VETERINARIO` ON `CONSULTAS` (`VeterinarioId`);
CREATE INDEX `IX_CONSULTAS_PET` ON `CONSULTAS` (`PetId`);
CREATE INDEX `IX_EXAMES_CONSULTA` ON `EXAMES` (`ConsultaId`);
CREATE INDEX `IX_PRESCRICOES_CONSULTA` ON `PRESCRICOES` (`ConsultaId`);
CREATE INDEX `IX_MEDICAMENTOS_PRESCRICAO` ON `MEDICAMENTOS` (`PrescricaoId`);
CREATE INDEX `IX_HISTORICO_PESOS_PET` ON `HISTORICO_PESOS` (`PetId`);
CREATE INDEX `IX_LEMBRETES_TUTOR` ON `LEMBRETES` (`TutorId`);
CREATE INDEX `IX_LEMBRETES_PET` ON `LEMBRETES` (`PetId`);
CREATE INDEX `IX_RECOMENDACOES_PET` ON `RECOMENDACOES` (`PetId`);
CREATE INDEX `IX_VACINACOES_PET` ON `VACINACOES` (`PetId`);
CREATE INDEX `IX_VACINACOES_VETERINARIO` ON `VACINACOES` (`VeterinarioId`);
CREATE INDEX `IX_VERMIFUGACOES_PET` ON `VERMIFUGACOES` (`PetId`);
CREATE INDEX `IX_VERMIFUGACOES_VETERINARIO` ON `VERMIFUGACOES` (`VeterinarioId`);
CREATE INDEX `IX_COMPORTAMENTOS_PET` ON `COMPORTAMENTOS` (`PetId`);
